create database companydb;
create table employees(employeeId int primary key,first_name varchar(50),last_name varchar(50),age int,department varchar(50),salary decimal(10,2),hire_date date);
desc employees;
insert into employees values(1,'vinayak','ambore',23,'ece',44000,'2023-07-01');
insert into employees values(2,'raj','lehr',13,'eee',24000,'2023-07-02'),(3,'ram','seti',31,'mech',12000,'2023-07-01'),(4,'jay','kumar',45,'staff',2400,'2023-05-02'),(5,'great','khali',60,'wwe',124000,'2010-07-30'),(6,'mr','bean',34,'comedy',22000,'2002-01-23'),(7,'virat','kohli',32,'cricket',300000,'2008-06-13'),(8,'AB','devilliers',35,'cricket',123000,'2007-07-17'),(9,'black','boon',23,'magic',45000,'2023-08-23'),(10,'sam','luther',34,'football',24000,'2023-02-06');
select * from employees;
select first_name,last_name from employees where age>30;
select employeeId,first_name,last_name from employees where department='ece' or department='cricket';
select employeeId,first_name,last_name from employees where hire_date between '2023-07-01' and '2023-07-30';
select first_name,last_name from employees where first_name like 'r%';
select first_name,last_name from employees where last_name like '%kohli';
select employeeId,first_name,last_name from employees where age=25 or age=30 or age=35;
select avg(salary) as average from employees;
select salary from employees where department='cricket';
select count('ece');
select employeeId,first_name,last_name from employees where year(hire_date);
select employeeId,first_name,last_name from employees order by salary desc;
select * from employees limit 5;
select employeeId,first_name,last_name from employees where salary between 40000 and 100000;
select employeeId,first_name,last_name from employees where first_name like 'vinayak%' or 'jane%';
select employeeId,first_name,last_name from employees where last_name<>'smith' and age between 25 and 40; 
select employeeId,first_name,last_name from employees where department in ('ece','cricket') and age>=35;
select employeeId,first_name,last_name from employees where hire_date>= DATE_SUB(CURDATE(), INTERVAL 6 MONTH);
select employeeId,first_name,last_name from employees where first_name like '%a%';
select employeeId,first_name,last_name from employees where last_name like 's___' and length(last_name)=4;
select employeeId,first_name,last_name from employees where month(hire_date)=2;
select employeeId,first_name,last_name from employees where age>(select avg(age) from employees);
select employeeId,first_name,last_name from employees where salary>(select max(salary) from employees where department='cricket');
select employeeId,first_name,last_name from employees where hire_date>'2023-06-01' and '2023-07-01';
select employeeId,first_name,last_name from employees where last_name like '%ohl%';
select employeeId,first_name,last_name from employees where department='cricket' and not age=40;
select employeeId,first_name,last_name from employees where salary>(select avg(salary) from employees where department='cricket');
select employeeId,first_name,last_name from employees where year(hire_date)='2023' and month(hire_date)=2 or 3;
select employeeId,first_name,last_name from employees where first_name like 'r%' and last_name like '%t%';
select employeeId,first_name,last_name from employees where age<30 and salary>40000;
select employeeId,first_name,last_name from employees where age between 25 and 35  and  department='eee';
select employeeId,first_name,last_name from employees where day(hire_date)=1;
select employeeId,first_name,last_name from employees where last_name like '%smi%';
select employeeId,first_name,last_name from employees where not age between 30 and 40;
select employeeId,first_name,last_name from employees where length(first_name)=3;